apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nlp-insights.fullname" . }}
  labels:
    {{- include "nlp-insights.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nlp-insights.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nlp-insights.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nlp-insights
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        env:
          - name: QUICKUMLS_ENABLE_CONFIG
            value: {{ quote .Values.nlpservice.quickumls.enableconfig }}
          - name: QUICKUMLS_NAME
            value: {{ .Values.nlpservice.quickumls.name }}
          - name: QUICKUMLS_ENDPOINT
            value: {{ .Values.nlpservice.quickumls.endpoint }}
          - name: ACD_ENABLE_CONFIG
            value: {{ quote .Values.nlpservice.acd.enableconfig }}
          - name: ACD_NAME
            value: {{ .Values.nlpservice.acd.name }}
          - name: ACD_ENDPOINT
            value: {{ .Values.nlpservice.acd.endpoint }}
          - name: ACD_API_KEY
            value: {{ .Values.nlpservice.acd.apikey }}
          - name: ACD_FLOW
            value: {{ .Values.nlpservice.acd.flow }}
          - name: NLP_SERVICE_DEFAULT
            value: {{ .Values.nlpservice.default }}
