{{- if .Values.ingress.enabled -}}
{{- if index .Values "deid" "enabled" -}}
{{- $ingressPort := .Values.deid.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-deid-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deid.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}.{{ .Release.Name }}-deid.{{ .Values.ingress.subdomain}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-deid
              servicePort: {{ $ingressPort }}
{{- end }}
{{- end }}
