{{- if .Values.ingress.enabled -}}
{{- if index .Values "kube-prometheus-stack" "enabled" -}}
{{- $ingressPort := index .Values "kube-prometheus-stack" "grafana" "service" "portName" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}.{{ .Release.Name }}-grafana.{{ .Values.ingress.subdomain}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-grafana
              servicePort: {{ $ingressPort }}
{{- end }}
{{- end }}
