{{- if .Values.ingress.enabled -}}
{{- if .Values.nifi.enabled -}}
{{- $ingressPort := .Values.nifi.service.httpInputPort -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nifi-http-post-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.nifi.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}.{{ .Release.Name }}-nifi-http-post.{{ .Values.ingress.subdomain}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-nifi
              servicePort: {{ $ingressPort }}
{{- end }}
{{- end }}
