{{- if .Values.nifi.enabled -}}
{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.nifi.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nifi
  namespace: {{ .Release.Namespace }}
  {{- with .Values.nifi.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /nifi
            pathType: ImplementationSpecific
            backend:
              service:
                name: alvearie-nifi
                port: 
                  number: {{ $ingressPort }}
{{- end }}
{{- end }}